version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './prometheus/rules:/etc/prometheus/rules'
      - 'prom-tsdb:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=60d'
    ports:
      - 9090:9090
    restart: always
    networks:
      - prom
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - './alertmanager:/etc/alertmanager'
    ports:
      - 9093:9093
    restart: always
    networks:
      - prom

  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - 'grafana-pv:/var/lib/grafana'
    ports:
      - 3000:3000
    restart: always
    networks:
      - prom
    depends_on:
      - prometheus

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.17.0
    container_name: blackbox_exporter
    volumes:
      - './blackbox_exporter:/config'
    ports:
      - 9115:9115
    command:
       - '--config.file=/config/blackbox.yml'
    restart: always
    networks:
      - prom

volumes:
  grafana-pv:
    driver: local
  prom-tsdb:
    driver: local

networks:
  prom:
    ipam:
      driver: default
      config:
      - subnet: "172.21.18.0/24"
